const ACCESS_TOKEN_EXPIRES = '15m'
const REFRESH_TOKEN_EXPIRES = '7d'

const SALT_ROUNDS = 10

const NEW_ORDER_STEP = 10.3

module.exports = {
  NEW_ORDER_STEP,
  ACCESS_TOKEN_EXPIRES,
  REFRESH_TOKEN_EXPIRES,
  SALT_ROUNDS,
}
